# Generated by Django 4.2.5 on 2023-09-17 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Характер отказа')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид поломки',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('factoryNumberOfMachine', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Зав. № машины')),
                ('factoryNumberOfEngine', models.CharField(max_length=128, verbose_name='Зав. № двигателя')),
                ('factoryNumberOfTransmission', models.CharField(max_length=128, verbose_name='Зав. № трансмиссии')),
                ('factoryNumberOfMainBridge', models.CharField(max_length=128, verbose_name='Зав. № ведущего моста')),
                ('factoryNumberOfSteerableBridge', models.CharField(max_length=128, verbose_name='Зав. № управляемого моста')),
                ('contract', models.CharField(max_length=128, verbose_name='Договор поставки №, дата')),
                ('dateOfShipment', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consumer', models.CharField(max_length=128, verbose_name='Грузополучатель')),
                ('operationAddress', models.CharField(max_length=128, verbose_name='Адрес поставки')),
                ('options', models.TextField(blank=True, verbose_name='Доп. опции')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Машина',
                'ordering': ['-dateOfShipment'],
            },
        ),
        migrations.CreateModel(
            name='ModelOfEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Модель двигателя')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='ModelOfMainBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Модель ведущего моста')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='ModelOfSteerableBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Модель управляемого моста')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='ModelOfTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Модель')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель',
            },
        ),
        migrations.CreateModel(
            name='ModelOfTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Модель трансмиссии')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель Трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Способ восстановления')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ Восстановления',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Вид ТО')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTO', models.DateField(verbose_name='Дата проведения ТО')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('numberOrderWork', models.CharField(max_length=128, verbose_name='№ заказ-наряда')),
                ('dateOrderWork', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='serviceapp.machine', verbose_name='Машина')),
                ('maintenanceServiceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyTO', to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceCompany', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('typeOfTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TypeofTO', to='serviceapp.typeofto', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое Обслуживание',
                'ordering': ['-dateOfTO'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='modelOfEngine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelOfEngine', to='serviceapp.modelofengine', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelOfMachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelOfTechnic', to='serviceapp.modeloftechnic', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelOfMainBridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelofMainBridge', to='serviceapp.modelofmainbridge', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelOfSteerableBridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelOfSteerableBridge', to='serviceapp.modelofsteerablebridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelOfTransmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelOfTransmission', to='serviceapp.modeloftransmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceCompany', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfFailure', models.DateField(verbose_name='Дата отказа')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('descriptionOfFailure', models.CharField(max_length=128, verbose_name='Описание отказа')),
                ('usedSpareParts', models.CharField(blank=True, max_length=128, verbose_name='Используемые запасные части')),
                ('dateOfRecovery', models.DateField(verbose_name='Дата восстановления')),
                ('downtimeOfMachine', models.IntegerField(blank=True, verbose_name='Время простоя')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_machine', to='serviceapp.machine', verbose_name='Машина')),
                ('nodeOfFailure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeoffailure', to='serviceapp.failuretype', verbose_name='Узел отказа')),
                ('recoveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoverymethod', to='serviceapp.recoverymethod', verbose_name='Способ восстановления')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_serviceCompany', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-dateOfFailure'],
            },
        ),
    ]
