# Generated by Django 4.2.5 on 2023-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failuretype',
            options={'verbose_name': 'Вид поломки', 'verbose_name_plural': 'Виды поломок'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-dateOfShipment'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='modelofengine',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателей'},
        ),
        migrations.AlterModelOptions(
            name='modelofmainbridge',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущих мостов'},
        ),
        migrations.AlterModelOptions(
            name='modelofsteerablebridge',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемых мостов'},
        ),
        migrations.AlterModelOptions(
            name='modeloftechnic',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='modeloftransmission',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссий'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Способ ремонта', 'verbose_name_plural': 'Способы ремонта'},
        ),
        migrations.AlterModelOptions(
            name='to',
            options={'ordering': ['-dateOfTO'], 'verbose_name': 'Техническое Обслуживание', 'verbose_name_plural': 'Техническое Обслуживание'},
        ),
        migrations.AlterModelOptions(
            name='typeofto',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
        migrations.AlterField(
            model_name='failuretype',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='failuretype',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='contract',
            field=models.CharField(max_length=128, verbose_name='Договор поставки №'),
        ),
        migrations.AlterField(
            model_name='modelofengine',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='modelofmainbridge',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='modelofsteerablebridge',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='modeloftechnic',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='modeloftransmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='typeofto',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
    ]
